build site:
  image: node :18
  stage: build
  script:
    - npm install --progress-false
    - npm run build
    artifacts:
    expire_in:1 week
    paths:
      -dist

unit test:
  image: node18
  stage: test
  script:
    - npm install --progress=false
    - npm run unit

deploy:
  image: ubuntu
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y rsync
    - rsync -rav --delete dist/ /home/bzc/page/
